server:
  servlet:
    context-path: api/v1/
spring:
  application:
    name: SharedOffice
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: ${SECRET_KEY}
  access-token-validity-in-seconds: 1800  # 30 minutes
  refresh-token-validity-in-seconds: 604800  # 7 days





