server:
  servlet:
    context-path: api/v1/
spring:
  application:
    name: SharedOffice
  datasource:
    url: jdbc:mysql://localhost:3306/SharedOffice
    username: springstudent
    password: springstudent
    driver-class-name: com.mysql.cj.jdbc.Driver
